### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by yegor256** [yegor256/jekyll-chatgpt-translate#30]
```
\u001b[1mTraceback\u001b[m (most recent call last):
	29: from /usr/local/rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
	28: from /usr/local/rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
	27: from /usr/local/rvm/gems/ruby-2.7.6/bin/jekyll:25:in `<main>'
	26: from /usr/local/rvm/gems/ruby-2.7.6/bin/jekyll:25:in `load'
	25: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
	24: from /usr/local/rvm/gems/ruby-2.7.6/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	23: from /usr/local/rvm/gems/ruby-2.7.6/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	22: from /usr/local/rvm/gems/ruby-2.7.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	21: from /usr/local/rvm/gems/ruby-2.7.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	20: from /usr/local/rvm/gems/ruby-2.7.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	19: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	18: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	17: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
	16: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	15: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
	14: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
	13: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
	12: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/site.rb:79:in `process'
	11: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `generate'
	10: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `each'
	 9: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-4.3.2/lib/jekyll/site.rb:193:in `block in generate'
	 8: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/generator.rb:62:in `generate'
	 7: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/generator.rb:62:in `each'
	 6: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/generator.rb:64:in `block in generate'
	 5: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/generator.rb:64:in `each'
	 4: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/generator.rb:96:in `block (2 levels) in generate'
	 3: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/chatgpt.rb:51:in `translate'
	 2: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/chatgpt.rb:51:in `map'
	 1: from /usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/chatgpt.rb:68:in `block in translate'
/usr/local/rvm/gems/ruby-2.7.6/gems/jekyll-chatgpt-translate-0.0.22/lib/jekyll-chatgpt-translate/chatgpt.rb:100:in `translate_par': \u001b[1mundefined method `split' for nil:NilClass (\u001b[1;4mNoMethodError\u001b[m\u001b[1m)\u001b[m

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.23`
