### ISSUE TITLE
window_length error

### ISSUE THREAD

**Issue by yegor256** [yegor256/jekyll-chatgpt-translate#63]
```
/usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/chatgpt.rb:97:in `>': \u001b[1mcomparison of Integer with String failed (\u001b[1;4mArgumentError\u001b[m\u001b[1m)\u001b[m

\u001b[1m        if already > window_length\u001b[m
\u001b[1m                     ^^^^^^^^^^^^^\u001b[m
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/chatgpt.rb:97:in `translate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:117:in `block (2 levels) in generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:66:in `each'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:66:in `block in generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:64:in `each'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:64:in `each_with_index'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.39/lib/jekyll-chatgpt-translate/generator.rb:64:in `generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-4.3.2/lib/jekyll/site.rb:193:in `block in generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `each'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-4.3.2/lib/jekyll/site.rb:79:in `process'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.41`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.41`
