### ISSUE TITLE
implicit conversion of Hash into String

### ISSUE THREAD

**Issue by yegor256** [yegor256/jekyll-chatgpt-translate#64]
```
/usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `initialize': \u001b[1mno implicit conversion of Hash into String (\u001b[1;4mTypeError\u001b[m\u001b[1m)\u001b[m

\u001b[1m    Parser.new(source, **(opts||{})).parse\u001b[m
\u001b[1m               ^^^^^^^^^^^^^^^^^^^^\u001b[m
	from /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `new'
	from /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/chatgpt.rb:135:in `translate_par'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/chatgpt.rb:114:in `translate_pars'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/chatgpt.rb:105:in `translate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:117:in `block (2 levels) in generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:66:in `each'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:66:in `block in generate'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:64:in `each'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:64:in `each_with_index'
	from /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.41/lib/jekyll-chatgpt-translate/generator.rb:64:in `generate'

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.42`
